page/urls.py
from django.urls import path
from . import views

app_name = 'page'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Тестовая страница
    path('test_page/', views.test_page, name='test_page'),
    # Страница для каждой темы
    path('<int:product_id>/ ', views.product, name='product'),
    # Страница для каталога
    path('select_product/<str:text>/', views.select_product, name='select_product'),
    # Страница аккаунта
    path('account/', views.account, name='account'),
]

server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('servachok/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('page.urls')),
]

# Добавляем обслуживание статических файлов в режиме разработки
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
	# Дефолтные URL аутентификации
	path('', include('django.contrib.auth.urls')),
	# Страница регестрации
	path('register/', views.register, name='register'),
]

page/models.py
from django.db import models

class Stuff_card(models.Model):
	image = models.ImageField(upload_to="image/")
	text = models.CharField(max_length=50)
	price = models.TextField()
	size = models.TextField()
	global_tag = models.TextField()
	local_tag = models.TextField()

	def __str__(self):
		return self.text 

users/models.py
from django.db import models

# Create your models here.

page/views.py
import time
from random import choice
from django.shortcuts import render
from .models import Stuff_card

cached_context = {}
last_time_update = 0

def refrash_index():
    global cached_context, last_time_update
    current_time = time.time()

    if current_time - last_time_update > 60 or current_time == None:
        objects = Stuff_card.objects.all()
        select_item = set()
        for i in range(1, 5):
            for_var = choice(objects)
            while for_var in select_item or for_var == objects.get(id=2) or for_var == objects.get(id=3):
                for_var = choice(objects)
            select_item.add(for_var)
            cached_context[f'stuff{i}'] = for_var

        last_time_update = current_time
        
    return cached_context


def index(request):
    """Главная страница"""
    context = refrash_index()
    return render(request, 'page/index.html', context)


def product(request, product_id):
    product = Stuff_card.objects.get(id=product_id)
    context = {'product': product}
    return render(request, 'page/product.html', context)


def select_product(request, text):
    products_list = Stuff_card.objects.all()
    sorted_product_list = set()
    for item in products_list:
        if item.global_tag == text or item.local_tag == text:
            sorted_product_list.add(item)

    context = {'sorted_product_list': sorted_product_list}
    return render(request, 'page/selected_product.html', context)


def test_page(request):
    """Страница для теста модели stuff_card"""
    stuff_card = Stuff_card.objects.all()
    context = {'stuff_card': stuff_card}
    return render(request, 'page/test_page.html', context)


def account(request):
    """Страница аккаунта"""
    return render(request, 'page/account.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
	"""Регестрация"""
	if request.method != 'POST':
		# Показать пустую форму регестрации
		form = UserCreationForm()
	else:
		# Обработка формы
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user =form.save()
			# Авторизировать пользователя и редиректнуть его
			login(request, new_user)
			return redirect('page:accont')

	# Показать пустую или недействительную форму
	context = {'form': form}
	return render(request, 'registration/register.html', context)

page/templates/page/account.html
{% extends 'page/base.html' %}

{% block title %}Аккаунт{% endblock %}

{% block content %}
	{% if user.is_authenticated %}
		<p class="hello">Привет, {{ user.username }}</p>
		<form method="post" action="{% url 'users:logout' %}">
	   		{% csrf_token %}
			<button type="submit" class="log-out">Log out</button>
		</form>
	{% else %}
		<p><a href="{% url 'users:login' %}" class="login">Login</a></p>
		<p><a href="{% url 'users:register' %}" class="register">Register</a></p>
	{% endif %}
{% endblock content %}

page/templates/page/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block title %}Магазин продуктов "Олежка"{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="shortcut icon" type="image/png" href="{% static 'css/media/favicon.ico'%}">
</head>
<body>
	<p>
		<a href="{% url 'page:index' %}" class="zxc">Главная страница</a>
	</p>
	<p>
		<a href="{% url 'page:account' %}" class="account">Аккаунт</a>
	</p>

	{% block content %}{% endblock content %}

</body>
</html>

page/templates/page/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    	<title>Магазин продуктов "Олежка"</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/modal.css' %}">
	<link rel="shortcut icon" type="image/png" href="{% static 'css/media/favicon.ico'%}">
</head>
<body>
	<footer class="footer">
        <div class="container">
            <p class="contact-item">Телефон: +380 (67) 999-99-99</p>
            <p class="contact-item">Email: sosun@gmail.com</p>
        </div>
    </footer>
	<h1><big>Магазин продуктов "Олежка"</big></h1>
   	<div class="button">
 		<a href="#" id="openModalBtn" class="qwerty"><big>Каталог продуктов</big></a>
 	</div>
	<a href="{% url 'page:account' %}" class="account">Аккаунт</a>
    <!-- Включаем содержимое всплывающего окна -->
    {% include 'page/modal_content.html' %}
    <!-- Ссылка для открытия модального окна -->
    <script src="{% static 'js/modal.js' %}"></script>

	<h2 class="qwerty"><big>Акции:</big></h2>

	<div class="flex">

		<div class="item">
			<h4>
				<a href="{% url 'page:product' stuff1.id %}" class="block">
					<img src="{{ stuff1.image.url }}">
				{{ stuff1.text }}</a>
			</h4>
			<p class="block">{{ stuff1.price }}</p>
			<p class="block">{{ stuff1.size }}</p>
		</div>

		<div class="item">
			<h4>
				<a href="{% url 'page:product' stuff2.id %}" class="block">
					<img src="{{ stuff2.image.url }}">
				{{ stuff2.text }}</a>
			</h4>
			<p class="block">{{ stuff2.price }}</p>
			<p class="block">{{ stuff2.size }}</p>
		</div>

		<div class="item">
			<h4>
				<a href="{% url 'page:product' stuff3.id %}" class="block">
					<img src="{{ stuff3.image.url }}">
				{{ stuff3.text }}</a>
			</h4>
			<p class="block">{{ stuff3.price }}</p>
			<p class="block">{{ stuff3.size }}</p>
		</div>

		<div class="item">
			<h4>
				<a href="{% url 'page:product' stuff4.id %}" class="block">
					<img src="{{ stuff4.image.url }}">
				{{ stuff4.text }}</a>
			</h4>
			<p class="block">{{ stuff4.price }}</p>
			<p class="block">{{ stuff4.size }}</p>
		</div>

	</div>

</body>
</html>	

page/templates/page/modal_content.html
<div id="myModal" class="modal">
    <div class="modal-content">
        <span class="close" id="closeModalBtn">&times;</span>
        <h2>Каталог продуктов</h2>
        <ul>
            <li>
                <a class="category" data-category="meat">Мясо</a>
                <ul class="subcategory" id="meat">
                    <li><a href="{% url 'page:select_product' 'meat' %}">Все в "Мясо"</a></li>
                    <li><a href="{% url 'page:select_product' 'pork' %}">Свинина</a></li>
                    <li><a href="{% url 'page:select_product' 'beef' %}">Говядина</a></li>
                    <li><a href="{% url 'page:select_product' 'poluty' %}">Птица</a></li>
                    <li><a href="{% url 'page:select_product' 'lamb' %}">Баранина</a></li>
                    <li><a href="{% url 'page:select_product' 'minced_meat' %}">Фарш</a></li>
                </ul>
            </li>
            <li>
                <a class="category" data-category="sausage">Колбаса и сосиски</a>
                <ul class="subcategory" id="sausage">
                    <li><a href="{% url 'page:select_product' 'sausage_and_frankfurters' %}">Все в "Колбаса и сосиски"</a></li>
                    <li><a href="{% url 'page:select_product' 'boiled_sausage' %}">Колбаса варенная</a></li>
                    <li><a href="{% url 'page:select_product' 'smoked_sausage' %}">Колбаса копченая</a></li>
                    <li><a href="{% url 'page:select_product' 'dry_cured_sausage' %}">Колбаса сырокопченая</a></li>
                    <li><a href="{% url 'page:select_product' 'frankfurters' %}">Сосиски</a></li>
                    <li><a href="{% url 'page:select_product' 'sausages_links' %}">Сардельки</a></li>
                </ul>
            </li>
            <li>
                <a class="category" data-category="grocery">Бакалия</a>
                <ul class="subcategory" id="grocery">
                    <li><a href="{% url 'page:select_product' 'groceries' %}">Все в "Бакалия"</a></li>
                    <li><a href="{% url 'page:select_product' 'pasta' %}">Макаронные изделия</a></li>
                    <li><a href="{% url 'page:select_product' 'oil_vinegar' %}">Олия и уксус</a></li>
                    <li><a href="{% url 'page:select_product' 'spices_and_marinades' %}">Приправы и маринады</a></li>
                    <li><a href="{% url 'page:select_product' 'breakfast_cereals' %}">Сухие завтраки</a></li>
                    <li><a href="{% url 'page:select_product' 'grains' %}">Крупы</a></li>
                </ul>
            </li>
            <li>
                <a class="category" data-category="fruit">Фрукты</a>
                <ul class="subcategory" id="fruit">
                    <li><a href="{% url 'page:select_product' 'fruits' %}">Все в "Фрукты"</a></li>
                    <li><a href="{% url 'page:select_product' 'apricots' %}">Абрикосы</a></li>
                    <li><a href="{% url 'page:select_product' 'pears' %}">Груши</a></li>
                    <li><a href="{% url 'page:select_product' 'apples' %}">Яблоки</a></li>
                    <li><a href="{% url 'page:select_product' 'peaches' %}">Персики</a></li>
                    <li><a href="{% url 'page:select_product' 'exotic_fruits' %}">Экзотические фрукты</a></li>
                    <li><a href="{% url 'page:select_product' 'dried_fruits' %}">Сухофрукты</a></li>
                    <li><a href="{% url 'page:select_product' 'berries' %}">Ягоды</a></li>
                    <li><a href="{% url 'page:select_product' 'citrus' %}">Цитрусовые</a></li>
                </ul>
            </li>
            <li>
                <a class="category" data-category="vegetables">Овощи</a>
                <ul class="subcategory" id="vegetables">
                    <li><a href="{% url 'page:select_product' 'vegetables' %}">Все в "Овощи"</a></li>
                    <li><a href="{% url 'page:select_product' 'tomatoes' %}">Помидоры</a></li>
                    <li><a href="{% url 'page:select_product' 'cucumbers' %}">Огурцы</a></li>
                    <li><a href="{% url 'page:select_product' 'zucchini' %}">Кабачок</a></li>
                    <li><a href="{% url 'page:select_product' 'eggplants' %}">Баклажан</a></li>
                    <li><a href="{% url 'page:select_product' 'onions' %}">Лук</a></li>
                    <li><a href="{% url 'page:select_product' 'green_onions' %}">Зеленый лук</a></li>
                    <li><a href="{% url 'page:select_product' 'garlic' %}">Чеснок</a></li>
                    <li><a href="{% url 'page:select_product' 'corn' %}">Кукуруза</a></li>
                    <li><a href="{% url 'page:select_product' 'cabbage' %}">Капуста</a></li>
                    <li><a href="{% url 'page:select_product' 'pumpkin' %}">Тыква</a></li>
                    <li><a href="{% url 'page:select_product' 'carrots' %}">Морковь</a></li>
                    <li><a href="{% url 'page:select_product' 'pappers' %}">Перец</a></li>
                    <li><a href="{% url 'page:select_product' 'beets' %}">Свекла</a></li>
                    <li><a href="{% url 'page:select_product' 'legumes' %}">Бобовые</a></li>
                    <li><a href="{% url 'page:select_product' 'potato' %}">Картошка</a></li>
                    <li><a href="{% url 'page:select_product' 'dill' %}">Укроп</a></li>
                </ul>
            </li>
            <li>
                <a class="category" data-category="baby-food">Детское питание</a>
                <ul class="subcategory" id="baby-food">
                    <li><a href="{% url 'page:select_product' 'baby_food' %}">Все в "Детское питание"</a></li>
                    <li><a href="{% url 'page:select_product' 'baby_purees' %}">Детское пюре</a></li>
                    <li><a href="{% url 'page:select_product' 'milk_formulas' %}">Молочные смеси</a></li>
                    <li><a href="{% url 'page:select_product' 'porridge' %}">Каши</a></li>
                    <li><a href="{% url 'page:select_product' 'baby_biscuits' %}">Детское печенье</a></li>
                </ul>
            </li>
            <li>
                <a class="category" data-category="bakery">Хлебобулочные изделия</a>
                <ul class="subcategory" id="bakery">
                    <li><a href="{% url 'page:select_product' 'bakery_product' %}">Все в "Хлебобулочные изделия"</a></li>
                    <li><a href="{% url 'page:select_product' 'croissant' %}">Круассан</a></li>
                    <li><a href="{% url 'page:select_product' 'bread_loaf' %}">Батон</a></li>
                    <li><a href="{% url 'page:select_product' 'baguette' %}">Багет</a></li>
                    <li><a href="{% url 'page:select_product' 'lavash' %}">Лаваш</a></li>
                    <li><a href="{% url 'page:select_product' 'pastries' %}">Выпечка</a></li>
                    <li><a href="{% url 'page:select_product' 'rusks_and_bagels' %}">Сухари и сушки</a></li>
                </ul>
            </li>
            <li>
                <a class="category" data-category="dairy-eggs">Молочная продукция и яйца</a>
                <ul class="subcategory" id="dairy-eggs">
                    <li><a href="{% url 'page:select_product' 'dairy_products_and_eggs' %}">Все в "Молочная продукция и яйца"</a></li>
                    <li><a href="{% url 'page:select_product' 'cottage_cheese' %}">Творог</a></li>
                    <li><a href="{% url 'page:select_product' 'milk' %}">Молоко</a></li>
                    <li><a href="{% url 'page:select_product' 'kefir' %}">Кефир</a></li>
                    <li><a href="{% url 'page:select_product' 'yogurt' %}">Йогурт</a></li>
                    <li><a href="{% url 'page:select_product' 'sour_cream' %}">Сметана</a></li>
                    <li><a href="{% url 'page:select_product' 'butter' %}">Сливочное масло</a></li>
                    <li><a href="{% url 'page:select_product' 'chicken_eggs' %}">Яйца куриные</a></li>
                    <li><a href="{% url 'page:select_product' 'quail_eggs' %}">Яйца перепелиные</a></li>
                </ul>
            </li>
            <li>
                <a class="category" data-category="cheese">Сыры</a>
                <ul class="subcategory" id="cheese">
                    <li><a href="{% url 'page:select_product' 'cheese' %}">Все в "Сыры"</a></li>
                    <li><a href="{% url 'page:select_product' 'mozzarella' %}">Моцарелла</a></li>
                    <li><a href="{% url 'page:select_product' 'roquefort' %}">Рокфор</a></li>
                    <li><a href="{% url 'page:select_product' 'dorblu' %}">Дорблю</a></li>
                    <li><a href="{% url 'page:select_product' 'cheddar' %}">Чеддер</a></li>
                    <li><a href="{% url 'page:select_product' 'feta' %}">Фета</a></li>
                    <li><a href="{% url 'page:select_product' 'gorgonzola' %}">Горгонзола</a></li>
                    <li><a href="{% url 'page:select_product' 'sweet_chease' %}">Сырок</a></li>
                </ul>
            </li>
            <li>
                <a class="category" data-category="fish-seafood">Рыба и морепродукты</a>
                <ul class="subcategory" id="fish-seafood">
                    <li><a href="{% url 'page:select_product' 'fish_and_seafood' %}">Все в "Рыба и морепродукты"</a></li>
                    <li><a href="{% url 'page:select_product' 'seafood' %}">Морепродукты</a></li>
                    <li><a href="{% url 'page:select_product' 'caviar' %}">Икра</a></li>
                    <li><a href="{% url 'page:select_product' 'crab_sticks' %}">Крабовые палочки</a></li>
                    <li><a href="{% url 'page:select_product' 'fish' %}">Рыба</a></li>
                </ul>
            </li>
            <li>
                <a class="category" data-category="non-alcoholic">Безалкогольные напитки</a>
                <ul class="subcategory" id="non-alcoholic">
                    <li><a href="{% url 'page:select_product' 'non_alcohol' %}">Все в "Безалкогольные напитки"</a></li>
                    <li><a href="{% url 'page:select_product' 'mineral_and_drinking_water' %}">Минеральная и питьевая вода</a></li>
                    <li><a href="{% url 'page:select_product' 'energy_drinks' %}">Энергетики</a></li>
                    <li><a href="{% url 'page:select_product' 'juices' %}">Соки</a></li>
                    <li><a href="{% url 'page:select_product' 'kvass' %}">Квас</a></li>
                    <li><a href="{% url 'page:select_product' 'soda' %}">Газировка</a></li>
                </ul>
            </li>
            <li>
                <a class="category" data-category="alcohol">Алкогольные напитки</a>
                <ul class="subcategory" id="alcohol">
                    <li><a href="{% url 'page:select_product' 'alcohol' %}">Все в "Алкогольные напитки"</a></li>
                    <li><a href="{% url 'page:select_product' 'vodka' %}">Водка</a></li>
                    <li><a href="{% url 'page:select_product' 'rum' %}">Ром</a></li>
                    <li><a href="{% url 'page:select_product' 'liquor' %}">Ликеры</a></li>
                    <li><a href="{% url 'page:select_product' 'beer' %}">Пиво</a></li>
                    <li><a href="{% url 'page:select_product' 'wine' %}">Вино</a></li>
                    <li><a href="{% url 'page:select_product' 'champagne' %}">Шампанское</a></li>
                </ul>
            </li>
            <li>
                <a class="category" data-category="sweets">Сладости</a>
                <ul class="subcategory" id="sweets">
                    <li><a href="{% url 'page:select_product' 'sweets' %}">Все в "Сладости"</a></li>
                    <li><a href="{% url 'page:select_product' 'candies' %}">Конфеты</a></li>
                    <li><a href="{% url 'page:select_product' 'chocolate' %}">Шоколад</a></li>
                    <li><a href="{% url 'page:select_product' 'cakes' %}">Торты</a></li>
                    <li><a href="{% url 'page:select_product' 'jellies' %}">Желе</a></li>
                    <li><a href="{% url 'page:select_product' 'cookies' %}">Печенье</a></li>
                    <li><a href="{% url 'page:select_product' 'biscuits' %}">Бисквиты</a></li>
                    <li><a href="{% url 'page:select_product' 'gum' %}">Жвачки</a></li>
                    <li><a href="{% url 'page:select_product' 'ice-cream' %}">Мороженое</a></li>
                </ul>
            </li>
            <li>
                <a class="category" data-category="snacks">Снеки</a>
                <ul class="subcategory" id="snacks">
                    <li><a href="{% url 'page:select_product' 'sneaks' %}">Все в "Снеки"</a></li>
                    <li><a href="{% url 'page:select_product' 'chips' %}">Чипсы</a></li>
                    <li><a href="{% url 'page:select_product' 'nuts' %}">Орешки</a></li>
                    <li><a href="{% url 'page:select_product' 'crackers' %}">Сухарики</a></li>
                    <li><a href="{% url 'page:select_product' 'popcorn' %}">Попкорн</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>

page/templates/page/product.html
{% extends 'page/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block title %}{{ product.text }}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block content %}
        <div class="product-container">
            <img src="{{ product.image.url }}" alt="{{ product.text }}" class="product-image">
            <div class="product-details">
                <p class="product-description">{{ product.text }}</p>
                <p class="product-price">Цена: {{ product.price }}</p>
                <p class="product-size">Вес: {{ product.size }}</p>
            </div>
        </div>
    {% endblock content %}
</body>
</html>

page/templates/page/selected_product.html
{% extends 'page/base.html' %}
{% load static %}


{% block content %}
    <div class="product-list">
        {% for product in sorted_product_list %}
            <div class="product-container">
                <img src="{{ product.image.url }}" alt="{{ product.text }}" class="product-image">
                <div class="product-details">
                    <p class="product-description">{{ product.text }}</p>
                    <p class="product-price">Цена: {{ product.price }}</p>
                    <p class="product-size">Вес: {{ product.size }}</p>
                </div>
            </div>
        {% empty %}
            <p class="no-product">Пока товара не завезли</p>
        {% endfor %}
    </div>
{% endblock content %}

page/templates/page/test_page.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	{% for stuff in stuff_card %}
		<h1>Linux</h1>
		<img src="{{ stuff.image.url }}">
		<p>{{ stuff.text }}</p>
		<p>{{ stuff.price }}</p>
		<p>{{ stuff.size }}</p>
		<p>{{ stuff.global_tag }}
		<p>{{ stuff.local_tag }}</p>
	{% endfor %}
</body>